name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
    - name: Checkout repository code 
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs 
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    
    - name: Install dependecies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev 
    
    - name: Test with tox
      run: tox

    - name: Setup node.js for pyright 
      uses: actions/setup-node@v1
      with:
        node-version: "12"

    - name: Run type checking with pyright 
      run: |
        npm install -g pyright 
        pipenv run typecheck 
